### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [flatiron/revalidator#102]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
/*! 
* revalidator-v0.3.1. 
* Licensed under the Apache 2.0 License. 
*/

**Comment by Swaagie** [comment]
Each file will not be prepended with the license, it adds unnecessary overhead. The license is included with the package on npm and it's clearly stated in the pkg.json.
