### ISSUE TITLE
Validate confirmation field

### ISSUE THREAD

**Issue by brian-gates** [flatiron/revalidator#54]
Would love to see logic to support validating a password confirmation field.  Perhaps something like this:

```
validate({password: 'foo', passwordConfirm: 'bar'}, { properties: { passwordConfirm: { match: 'password' } } }
```

**Comment by anton6** [comment]
So how do you currently test repeated password using revalidator?

**Comment by anton6** [comment]
ok, managed to do this using **conform**

```
conform: (repeatPassword, context) => (
    repeatPassword === context.password
),
```

I think that current documentation does not explain that conform field has access to the context.
