### ISSUE TITLE
Possible bug and fix when validating non-required field with "email" format

### ISSUE THREAD

**Issue by fbernhard** [flatiron/revalidator#74]
I am not sure if this is a bug or intended. Given the following schema property:

```
txtEmail : {
    required : false,
    allowEmpty: true,
    type : "string",
    format : "email",
}
```

revalidator returns a validation error if the field _txtEmail_ is empty, even though _required_ is set to false and _allowEmpty_ to true.

The following fixes the issue for me:

```
$ diff revalidator-orig.js revalidator.js 
233c233
<     if (value === undefined) {

---
>     if (value === undefined || value === '') {
```

**Comment by Anahkiasen** [comment]
@Swaagie Not sure if it's a regression but that doesn't seem to be working:

``` js
const validator = require('revalidator').validate(
    {
        email: '',
    },
    {
        properties: {
            email: {
                format: 'email',
                minLength: 2,
            },
        },
    }
);

console.log(validator.errors);
// [
//     {
//         "attribute": "format",
//         "property": "email",
//         "expected": "email",
//         "actual": "",
//         "message": "is not a valid email"
//     }
```

**Comment by Anahkiasen** [comment]
Property format is checked on [line 258](https://github.com/flatiron/revalidator/blob/master/lib/revalidator.js#L278) way before length on [line 325](https://github.com/flatiron/revalidator/blob/master/lib/revalidator.js#L325) so I don't see anything preventing the error from being thrown if the string is empty.

EDIT: Did a `bisect` on the codebase, ab92b7a4d7cead508f866bcc951c48acd647beb4 seems to be the commit that broke it
